version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODEMON_APP=${NODEMON_APP}
        - PORT=${APP_EXTERNAL_PORT}
    image: ${APP_NAME}
    container_name: ${APP_NAME}_server
    restart: always
    ports:
      - "3333:3333"
      - "7000:7000"
    volumes:
      - ./:/root/app
    command: >
      sh -c "nodemon"
    networks:
      - videostream

networks:
  videostream:
    driver: bridge
