version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - NODEMON_APP=${NODEMON_APP}
        - PORT=${APP_EXTERNAL_PORT}
    image: ${APP_NAME}
    container_name: ${APP_NAME}_server
    restart: always
    ports:
      - "3333:3333"
      - "42001:42001"
      - "42002:42002"
      - "42003:42003"
      - "42004:42004"
      - "42005:42005"
    volumes:
      - ./:/root/src
      - ./:/root/node_modules
    command: >
      sh -c "nodemon"
    networks:
      - videostream

networks:
  videostream:
    driver: bridge
